language: elixir
elixir:
  - 1.6
otp_release:
  - 20.1
addons:
  apt:
    packages:
      - cargo
sudo: false
before_cache:
  - rm -r _build/dev/lib/overdiscord
cache:
  directories:
    - deps
    - _build
    - $HOME/.cargo
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
before_script:
  - mix deps.get
  - mix deps.compile
  - echo Meeseeks is broken currently, patching it...
  - sed -i 's|rustler .*|rustler = "^0.16"|' deps/meeseeks_html5ever/native/meeseeks_html5ever_nif/Cargo.toml
  - echo Meeseeks patching is complete
script:
  - mix compile # test
  - mix format --check-formatted
after_script:
  - mix inch.report
notifications:
  recipients:
    - overminddl1@gmail.com
